name: Push to Luarocks

on:
  push:
    release:
      types:
        - created
    tags:
      - '*'
  workflow_dispatch:

jobs:
  luarocks-upload:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to count the commits
      - name: Get Version
        run: echo "LUAROCKS_VERSION=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          version: ${{ env.LUAROCKS_VERSION }}
          test_interpreters: null
          summary: "A set of utility functions for Neovim plugins."
          detailed_description: |
            This repository contains a small set of nicities for performing repetitive tasks within Neovim.
            This set may shrink further as the features are included in other, larger "utility kits".

            The code you see in this repository is primarily used within Neorg.
            All functions are annotated using LuaCATS.
